name: AniList readme workflow
on:
  schedule:
    # Runs every hour
    - cron: "0 * * * *"
  workflow_dispatch: # for manual debuging

jobs:
  update-readme-with-anilist:
    name: Update README with latest AniList activites
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: AniList readme workflow
        uses: pxseu/anilist-readme@senpai # latest version
        with:
          user_name: "YogaPranata"
          max_post_count: 10
          timezone: "Asia/Jakarta"
