name: Sync AniList favorites
on:
  schedule:
    # Runs every hour
    - cron: "0 * * * *"
  workflow_dispatch: # for manual debuging

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - uses: actions/cache@v3
        name: Configure pip caching
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/scripts/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install Python dependencies
        run: |
          python -m pip install -r ./scripts/requirements.txt
      - name: Update AniList
        env:
          ANILIST_TOKEN: ${{ secrets.ANILIST_TOKEN }}
        run: |-
          python ./scripts/anilist_favorites.py
          cat AniList.md
      - name: Commit and push if changed
        env:
          GITHUB_TOKEN: ${{ secrets.PUSH_TOKEN }}
        run: |-
          git pull
          git diff
          git config --global user.email "yoga@isekai.eu.org"
          git config --global user.name "Yoga Pranata"
          git add -A
          git commit -m "Kawaii desune~" || exit 0
          git remote set-url --push origin https://zYxDevs:$GITHUB_TOKEN@github.com/zYxDevs/zYxDevs
          git push
